# Generated by Django 4.1 on 2022-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='thumbnails',
            field=models.FileField(blank=True, default='https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg', null=True, upload_to=''),
        ),
    ]
