# Generated by Django 4.1 on 2022-09-19 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_template_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
