# Generated by Django 4.1 on 2022-09-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_usertemplate_created_at_usertemplate_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemplate',
            name='updated_at',
        ),
    ]
