# Generated by Django 4.1 on 2022-12-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_usertemplate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
