# Generated by Django 4.1 on 2022-12-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_usertemplate_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(blank=True, default='none', null=True, upload_to=''),
        ),
    ]
